name:                ServHs
version:             0.1.0.0
github:              "Tehnix/ServHs"
license:             BSD3
author:              "Christian Laustsen"
maintainer:          "ckl@codetalk.io"
copyright:           "2018 Christian Laustsen"

description:         Please see the README on GitHub at <https://github.com/Tehnix/ServHs#readme>
extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- serverless-haskell

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
  dependencies:
    - aeson
    - lens
    - unordered-containers
    - text

executables:
  entry:
    main:                Entry.hs
    source-dirs:         app
    other-modules: []
    ghc-options: &ghc-exe-opts
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
    - ServHs
  gateway-entry:
    main:                GatewayEntry.hs
    source-dirs:         app
    other-modules: []
    ghc-options: *ghc-exe-opts
    dependencies:
    - ServHs

tests:
  ServHs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: *ghc-exe-opts
    dependencies:
    - ServHs
